# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'make_mail1234.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(539, 467)
        Dialog.setStyleSheet("background-color: rgb(98, 98, 98);")
        self.recipient = QtWidgets.QTextEdit(Dialog)
        self.recipient.setGeometry(QtCore.QRect(0, 40, 541, 41))
        self.recipient.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.recipient.setObjectName("recipient")
        self.snippet = QtWidgets.QTextEdit(Dialog)
        self.snippet.setGeometry(QtCore.QRect(0, 80, 541, 41))
        self.snippet.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.snippet.setObjectName("snippet")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 541, 41))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 406, 541, 61))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.send = QtWidgets.QPushButton(Dialog)
        self.send.setGeometry(QtCore.QRect(0, 420, 121, 41))
        self.send.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(13, 119, 212);")
        self.send.setObjectName("send")
        self.attach = QtWidgets.QPushButton(Dialog)
        self.attach.setGeometry(QtCore.QRect(150, 420, 41, 41))
        self.attach.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.attach.setObjectName("attach")
        self.draft = QtWidgets.QPushButton(Dialog)
        self.draft.setGeometry(QtCore.QRect(490, 420, 41, 41))
        self.draft.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.draft.setObjectName("draft")
        self.main_text = QtWidgets.QLineEdit(Dialog)
        self.main_text.setGeometry(QtCore.QRect(0, 120, 541, 291))
        self.main_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_text.setObjectName("main_text")
        self.files = QtWidgets.QLineEdit(Dialog)
        self.files.setGeometry(QtCore.QRect(200, 420, 201, 41))
        self.files.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.files.setObjectName("files")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Новое сообщение"))
        self.send.setText(_translate("Dialog", "Отправить"))
        self.attach.setText(_translate("Dialog", "📎"))
        self.draft.setText(_translate("Dialog", "🗑"))
