# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_html.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
"""
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView


class PageHtml(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(490, 540)
        self.save_att = QtWidgets.QPushButton(Dialog)
        self.save_att.setGeometry(QtCore.QRect(10, 492, 41, 41))
        self.save_att.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n""font: 75 26pt \"MS Shell Dlg 2\";")
        self.save_att.setObjectName("save_att")
        self.html_area = QWebEngineView(Dialog)
        self.html_area.setGeometry(QtCore.QRect(10, 10, 471, 471))
        self.html_area.setObjectName("html_area")
        PageHtml.retranslateUi(self, Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.save_att.setText(_translate("Dialog", "⤓"))

"""

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView


class PageHtml(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(490, 540)
        Dialog.setStyleSheet("background-color: rgb(103, 103, 103);")
        self.save_att = QtWidgets.QPushButton(Dialog)
        self.save_att.setGeometry(QtCore.QRect(10, 490, 41, 41))
        self.save_att.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\nbackground-color: rgb(185, 185, 185);\nfont: 75 26pt \"MS Shell Dlg 2\";")
        self.save_att.setObjectName("save_att")
        self.html_area = QWebEngineView(Dialog)
        self.html_area.setGeometry(QtCore.QRect(10, 10, 471, 471))
        self.html_area.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.html_area.setObjectName("html_area")
        self.resume = QtWidgets.QPushButton(Dialog)
        self.resume.setGeometry(QtCore.QRect(60, 490, 71, 41))
        self.resume.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\nbackground-color: rgb(185, 185, 185);")
        self.resume.setObjectName("resume")

        PageHtml.retranslateUi(self, Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.save_att.setText(_translate("Dialog", "⤓"))
        self.resume.setText(_translate("Dialog", "Далее"))
