from PyQt5 import QtCore, QtGui, QtWidgets


class MainW(object):
    def setupUi(self, Dialog, theme):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(983, 613)
        Dialog.setStyleSheet(["background-color: rgb(255, 255, 255);", "background-color: rgb(15, 15, 15);"][theme])
        self.list_of_mails = QtWidgets.QTableWidget(Dialog)
        self.list_of_mails.setGeometry(QtCore.QRect(180, 80, 801, 521))
        self.list_of_mails.setObjectName("list_of_mails")
        self.list_of_mails.setColumnCount(1)
        self.list_of_mails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.list_of_mails.setHorizontalHeaderItem(0, item)
        self.make_mail = QtWidgets.QPushButton(Dialog)
        self.make_mail.setGeometry(QtCore.QRect(10, 80, 111, 41))
        self.make_mail.setStyleSheet(["color: rgb(255, 0, 0);\nfont: 11pt \"MS Shell Dlg 2\";", 'color: rgb(255, 255, 255);\nfont: 11pt "MS Shell Dlg 2";\nbackground-color: rgb(197,34,30);'][theme])
        self.make_mail.setObjectName("make_mail")
        self.update = QtWidgets.QPushButton(Dialog)
        self.update.setGeometry(QtCore.QRect(130, 80, 41, 41))
        self.update.setStyleSheet(["font: 14pt \"MS Shell Dlg 2\";", 'font: 14pt "MS Shell Dlg 2";\nbackground-color: rgb(251,188,4);\ncolor: rgb(0, 0, 0);'][theme])
        self.update.setObjectName("update")
        self.search_text = QtWidgets.QLineEdit(Dialog)
        self.search_text.setGeometry(QtCore.QRect(182, 10, 571, 41))
        self.search_text.setStyleSheet(["font: 12pt \"MS Shell Dlg 2\";\nbackground-color: rgb(226, 226, 226);", "font: 14pt \"MS Shell Dlg 2\";\nbackground-color: rgb(95, 95, 95);\ncolor: rgb(255, 255, 255);"][theme])
        self.search_text.setText("")
        self.search_text.setObjectName("search_text")
        self.search = QtWidgets.QPushButton(Dialog)
        self.search.setGeometry(QtCore.QRect(760, 10, 41, 41))
        self.search.setStyleSheet(["font: 14pt \"MS Shell Dlg 2\";", 'font: 14pt "MS Shell Dlg 2";\nbackground-color: rgb(251,188,4);\ncolor: rgb(0, 0, 0);'][theme])
        self.search.setObjectName("search")
        self.all_mail = QtWidgets.QPushButton(Dialog)
        self.all_mail.setGeometry(QtCore.QRect(10, 140, 161, 41))
        self.all_mail.setStyleSheet(["color: rgb(255, 0, 0);\nfont: 11pt \"MS Shell Dlg 2\";", 'background-color: rgb(66,133,244);\ncolor: rgb(0,0,0);\nfont: 11pt "MS Shell Dlg 2";'][theme])
        self.all_mail.setObjectName("all_mail")
        self.incoming = QtWidgets.QPushButton(Dialog)
        self.incoming.setGeometry(QtCore.QRect(10, 190, 161, 41))
        self.incoming.setStyleSheet(["font: 9pt \"MS Shell Dlg 2\";", 'background-color: rgb(66,133,244);\ncolor: rgb(255,255,255);\nfont: 9pt "MS Shell Dlg 2";'][theme])
        self.incoming.setObjectName("incoming")
        self.sent = QtWidgets.QPushButton(Dialog)
        self.sent.setGeometry(QtCore.QRect(10, 240, 161, 41))
        self.sent.setStyleSheet(["font: 9pt \"MS Shell Dlg 2\";", 'background-color: rgb(66,133,244);\ncolor: rgb(255,255,255);\nfont: 9pt "MS Shell Dlg 2";'][theme])
        self.sent.setObjectName("sent")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 560, 160, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dark_theme = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.dark_theme.setStyleSheet(["font: 10pt \"MS Shell Dlg 2\";", 'font: 10pt "MS Shell Dlg 2";\ncolor: rgb(255, 255, 255);\nbackground-color: rgb(52,168,83);'][theme])
        self.dark_theme.setObjectName("dark_theme")
        self.gridLayout.addWidget(self.dark_theme, 2, 0, 1, 1)
        self.classic_theme = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.classic_theme.setStyleSheet(["font: 10pt \"MS Shell Dlg 2\";", 'font: 10pt "MS Shell Dlg 2";\ncolor: rgb(255, 255, 255);\nbackground-color: rgb(52,168,83);'][theme])
        self.classic_theme.setObjectName("classic_theme")
        if theme == 0:
            self.classic_theme.click()
        else:
            self.dark_theme.click()
        self.gridLayout.addWidget(self.classic_theme, 1, 0, 1, 1)
        self.image = QtWidgets.QLabel(self)
        self.image.move(20, 15)
        self.image.resize(109, 40)
        self.image.setPixmap(QtGui.QPixmap('files/logo.png'))
        self.drafts = QtWidgets.QComboBox(Dialog)
        self.drafts.setGeometry(QtCore.QRect(10, 330, 161, 41))
        self.drafts.setObjectName("drafts")
        if theme == 1:
            self.drafts.setStyleSheet('background-color: rgb(66,133,244);\ncolor: rgb(255,255,255);')
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 295, 81, 31))
        self.label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\ncolor: rgb(121, 121, 121);")
        self.label_2.setObjectName("label_2")
        MainW.retranslateUi(self, Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Gmail"))
        self.search_text.setPlaceholderText(_translate("Dialog", 'Поиск по всем цепочкам'))
        self.make_mail.setText(_translate("Dialog", "🖊 Написать"))
        self.update.setText(_translate("Dialog", "⟳"))
        self.search.setText(_translate("Dialog", "🔍"))
        self.all_mail.setText(_translate("Dialog", "Вся почта"))
        self.incoming.setText(_translate("Dialog", "Входящие"))
        self.sent.setText(_translate("Dialog", "Отправленные"))
        self.dark_theme.setText(_translate("Dialog", "Темная тема"))
        self.classic_theme.setText(_translate("Dialog", "Светлая тема"))
        self.label_2.setText(_translate("Dialog", "Черновики"))
